In [1]:
!pip install opencv-python


     |████████████████████████████████| 53.9 MB 28 kB/s eta 0:00:013     |██████▍                         | 10.7 MB 4.9 MB/s eta 0:00:09


In [1]:
import cv2
import numpy as np

# Laden der YOLO-Modelldateien
net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")

# Definieren der Klassen, die von YOLO erkannt werden sollen
classes = []
with open("coco.names", "r") as f:
    classes = [line.strip() for line in f.readlines()]
    #print(classes)

# Definieren von Farben für jede Klasse
colors = np.random.uniform(0, 255, size=(len(classes), 3))

# Öffnen der Webcam
cap = cv2.VideoCapture(0)

while True:
    # Lesen des aktuellen Frames aus der Webcam
    ret, frame = cap.read()

    # Skalieren des Bildes auf die Größe, die vom YOLO-Modell erwartet wird
    blob = cv2.dnn.blobFromImage(frame, 1/255, (416, 416), swapRB=True, crop=False)

    # Setzen des Blob als Eingabe für das YOLO-Modell
    net.setInput(blob)

    # Durchführen der Vorhersage auf dem Modell
    outs = net.forward(net.getUnconnectedOutLayersNames())
    print(outs)
    
    count = 0
    boxes = []
    confidences = []
    class_ids = []


    # Verarbeiten der Vorhersagen und Zeichnen der Bounding Boxes auf das Bild
    for output in outs:
        for detection in output:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]

            if class_id == 0 and confidence > 0.5:
                center_x = int(detection[0] * frame.shape[1])
                center_y = int(detection[1] * frame.shape[0])
                w = int(detection[2] * frame.shape[1])
                h = int(detection[3] * frame.shape[0])

                x = int(center_x - w/2)
                y = int(center_y - h/2)
                
                #x, y, w, h = detection[:4] * np.array([frame.shape[1], frame.shape[0], frame.shape[1], frame.shape[0]])
                boxes.append([x-w/2, y-h/2, w, h])
                confidences.append(float(confidence))
                class_ids.append(class_id)

                cv2.rectangle(frame, (x, y), (x + w, y + h), colors[class_id], 2)
                
                #indices = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
                #for i in indices:
                    #i = i[0]
                 #   x, y, w, h = boxes[i]
                  #  cv2.rectangle(frame, (int(x), int(y)), (int(x+w), int(y+h)), (0,255,0), 2)

                count = count+1
                font = cv2.FONT_HERSHEY_SIMPLEX
                cv2.putText(frame, str(count), (10,450), font, 3, (255, 0, 0), 2, cv2.LINE_AA)
                #print(count)
                
                if count >= 2:
                    font = cv2.FONT_HERSHEY_SIMPLEX
                    cv2.putText(frame, 'Zu viele Personen!', (5,150), font, 3, (0, 0, 255), 2, cv2.LINE_AA)
                    
    # Anzeigen des Bildes mit den Bounding Boxes
    cv2.imshow("Webcam", frame)

    # Abbrechen der Schleife bei Drücken der 'q'-Taste
    if cv2.waitKey(1) == ord('q'):
        break
        
# Freigeben der Ressourcen
cap.release()
cv2.destroyAllWindows()


(array([[0.04212145, 0.02837655, 0.27172115, ..., 0.        , 0.        ,
        0.        ],
       [0.05252911, 0.03126455, 0.23786497, ..., 0.        , 0.        ,
        0.        ],
       [0.05232978, 0.02825483, 0.9413377 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.95276886, 0.9476136 , 0.38821995, ..., 0.        , 0.        ,
        0.        ],
       [0.95792335, 0.96119857, 0.3085931 , ..., 0.        , 0.        ,
        0.        ],
       [0.96749485, 0.96580505, 0.78431934, ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02752028, 0.02339119, 0.05965276, ..., 0.        , 0.        ,
        0.        ],
       [0.01699163, 0.02352694, 0.215115  , ..., 0.        , 0.        ,
        0.        ],
       [0.02848134, 0.01746893, 0.09099638, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9810047 , 0.97406685, 0.03863037, ..., 0.        , 0.        ,
        0.        ],
       [0.9797596 

(array([[0.02399047, 0.03743715, 0.36631107, ..., 0.        , 0.        ,
        0.        ],
       [0.03627827, 0.0324611 , 0.25539705, ..., 0.        , 0.        ,
        0.        ],
       [0.0465109 , 0.03617626, 0.7529835 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9536164 , 0.9470241 , 0.37829712, ..., 0.        , 0.        ,
        0.        ],
       [0.9593032 , 0.9627682 , 0.30590168, ..., 0.        , 0.        ,
        0.        ],
       [0.9687566 , 0.96592736, 0.8001776 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02281892, 0.02190879, 0.0595964 , ..., 0.        , 0.        ,
        0.        ],
       [0.01493885, 0.02031844, 0.29972127, ..., 0.        , 0.        ,
        0.        ],
       [0.02134177, 0.0173452 , 0.07723801, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.98032105, 0.9741012 , 0.04093418, ..., 0.        , 0.        ,
        0.        ],
       [0.9797106 

(array([[0.02597756, 0.0391869 , 0.27839336, ..., 0.        , 0.        ,
        0.        ],
       [0.03580115, 0.0313468 , 0.23507307, ..., 0.        , 0.        ,
        0.        ],
       [0.042349  , 0.03529059, 0.7629525 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.95095897, 0.94601595, 0.3597507 , ..., 0.        , 0.        ,
        0.        ],
       [0.9588972 , 0.962723  , 0.30522954, ..., 0.        , 0.        ,
        0.        ],
       [0.9706742 , 0.96615833, 0.76456726, ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02373667, 0.02135855, 0.06159745, ..., 0.        , 0.        ,
        0.        ],
       [0.01382069, 0.02268022, 0.30112508, ..., 0.        , 0.        ,
        0.        ],
       [0.02033542, 0.01731554, 0.08298653, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9797877 , 0.974143  , 0.04078859, ..., 0.        , 0.        ,
        0.        ],
       [0.97960305

(array([[0.02775553, 0.03996068, 0.30546772, ..., 0.        , 0.        ,
        0.        ],
       [0.03550306, 0.03015692, 0.24352503, ..., 0.        , 0.        ,
        0.        ],
       [0.04518961, 0.03523497, 0.7602085 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9526916 , 0.9443683 , 0.34057015, ..., 0.        , 0.        ,
        0.        ],
       [0.9614642 , 0.9622912 , 0.30580312, ..., 0.        , 0.        ,
        0.        ],
       [0.96984386, 0.9637824 , 0.7937949 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02481483, 0.02337375, 0.06189505, ..., 0.        , 0.        ,
        0.        ],
       [0.01455196, 0.020852  , 0.28002357, ..., 0.        , 0.        ,
        0.        ],
       [0.02145102, 0.01777799, 0.07878216, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9774784 , 0.9737638 , 0.04402644, ..., 0.        , 0.        ,
        0.        ],
       [0.97875464

(array([[0.02863318, 0.04182165, 0.3335927 , ..., 0.        , 0.        ,
        0.        ],
       [0.03878491, 0.03131468, 0.2548319 , ..., 0.        , 0.        ,
        0.        ],
       [0.04842002, 0.03731181, 0.77218056, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9531685 , 0.9439873 , 0.35691768, ..., 0.        , 0.        ,
        0.        ],
       [0.9615288 , 0.964233  , 0.31214154, ..., 0.        , 0.        ,
        0.        ],
       [0.96844774, 0.96551096, 0.8026262 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02493986, 0.02360375, 0.06320374, ..., 0.        , 0.        ,
        0.        ],
       [0.01568171, 0.02232229, 0.26594445, ..., 0.        , 0.        ,
        0.        ],
       [0.02162324, 0.01738076, 0.07838842, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.97840697, 0.973816  , 0.04368866, ..., 0.        , 0.        ,
        0.        ],
       [0.97905546

(array([[0.02836443, 0.03824892, 0.28049356, ..., 0.        , 0.        ,
        0.        ],
       [0.04120775, 0.03276569, 0.22762614, ..., 0.        , 0.        ,
        0.        ],
       [0.04920525, 0.0348629 , 0.7849635 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9545794 , 0.9442182 , 0.3309371 , ..., 0.        , 0.        ,
        0.        ],
       [0.9618231 , 0.96466434, 0.29796678, ..., 0.        , 0.        ,
        0.        ],
       [0.9697825 , 0.9665613 , 0.78402966, ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02238266, 0.0197753 , 0.0624839 , ..., 0.        , 0.        ,
        0.        ],
       [0.01265685, 0.02208235, 0.26576662, ..., 0.        , 0.        ,
        0.        ],
       [0.0198796 , 0.01705367, 0.08494678, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.97801906, 0.9739083 , 0.04383512, ..., 0.        , 0.        ,
        0.        ],
       [0.9789852 

(array([[0.02634356, 0.04156631, 0.32573956, ..., 0.        , 0.        ,
        0.        ],
       [0.03736855, 0.02927745, 0.24137756, ..., 0.        , 0.        ,
        0.        ],
       [0.04684661, 0.03585487, 0.7705874 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9531092 , 0.94328177, 0.31976956, ..., 0.        , 0.        ,
        0.        ],
       [0.96116346, 0.96405995, 0.29396608, ..., 0.        , 0.        ,
        0.        ],
       [0.96948326, 0.9652427 , 0.7753755 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02493622, 0.0220378 , 0.0594965 , ..., 0.        , 0.        ,
        0.        ],
       [0.01417858, 0.02151928, 0.28722078, ..., 0.        , 0.        ,
        0.        ],
       [0.02127128, 0.01782474, 0.07896699, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9783191 , 0.9737403 , 0.04376135, ..., 0.        , 0.        ,
        0.        ],
       [0.97929096

(array([[0.02307808, 0.03854503, 0.28837493, ..., 0.        , 0.        ,
        0.        ],
       [0.0345384 , 0.03135001, 0.2356604 , ..., 0.        , 0.        ,
        0.        ],
       [0.04336099, 0.0338159 , 0.75840944, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.95227057, 0.94383913, 0.3319944 , ..., 0.        , 0.        ,
        0.        ],
       [0.9598757 , 0.9636619 , 0.29761437, ..., 0.        , 0.        ,
        0.        ],
       [0.9685906 , 0.96513647, 0.7737517 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02228379, 0.02070188, 0.06179639, ..., 0.        , 0.        ,
        0.        ],
       [0.01234423, 0.02039921, 0.2797998 , ..., 0.        , 0.        ,
        0.        ],
       [0.01906412, 0.01654562, 0.07813184, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9787547 , 0.9739565 , 0.04256278, ..., 0.        , 0.        ,
        0.        ],
       [0.9796204 

(array([[0.02279558, 0.03793621, 0.29257002, ..., 0.        , 0.        ,
        0.        ],
       [0.03550782, 0.03102254, 0.23748347, ..., 0.        , 0.        ,
        0.        ],
       [0.04389983, 0.0355075 , 0.78593093, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.952673  , 0.94387734, 0.32470867, ..., 0.        , 0.        ,
        0.        ],
       [0.96076673, 0.9628526 , 0.3000271 , ..., 0.        , 0.        ,
        0.        ],
       [0.9682595 , 0.9641601 , 0.8034043 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.02272247, 0.02090119, 0.06135358, ..., 0.        , 0.        ,
        0.        ],
       [0.01291864, 0.0222623 , 0.292989  , ..., 0.        , 0.        ,
        0.        ],
       [0.01981072, 0.01683979, 0.08190754, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.97869736, 0.97415453, 0.0434022 , ..., 0.        , 0.        ,
        0.        ],
       [0.97909045

(array([[0.02319504, 0.04019625, 0.2933493 , ..., 0.        , 0.        ,
        0.        ],
       [0.03399643, 0.03182242, 0.2290252 , ..., 0.        , 0.        ,
        0.        ],
       [0.04704159, 0.03541252, 0.7797381 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.95345825, 0.94345415, 0.31233412, ..., 0.        , 0.        ,
        0.        ],
       [0.9624033 , 0.96263397, 0.29630944, ..., 0.        , 0.        ,
        0.        ],
       [0.96986353, 0.9646819 , 0.77359253, ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.0238279 , 0.0228227 , 0.06099618, ..., 0.        , 0.        ,
        0.        ],
       [0.01438035, 0.0207007 , 0.28843015, ..., 0.        , 0.        ,
        0.        ],
       [0.01999288, 0.01697678, 0.07643701, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.97856295, 0.9739538 , 0.04256809, ..., 0.        , 0.        ,
        0.        ],
       [0.97943056

(array([[0.02475678, 0.04229941, 0.31885523, ..., 0.        , 0.        ,
        0.        ],
       [0.03553609, 0.027252  , 0.2370681 , ..., 0.        , 0.        ,
        0.        ],
       [0.04995071, 0.03722499, 0.78069645, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.953969  , 0.94399804, 0.3040151 , ..., 0.        , 0.        ,
        0.        ],
       [0.9624084 , 0.9632458 , 0.29262072, ..., 0.        , 0.        ,
        0.        ],
       [0.970087  , 0.964646  , 0.7831685 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[0.0227366 , 0.02139474, 0.06151133, ..., 0.        , 0.        ,
        0.        ],
       [0.01359328, 0.02204025, 0.26797175, ..., 0.        , 0.        ,
        0.        ],
       [0.0205066 , 0.01751522, 0.08263009, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.9791568 , 0.9739396 , 0.04240739, ..., 0.        , 0.        ,
        0.        ],
       [0.979504  